
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LanguageOut;

/** CUP generated class containing symbol constants. */
public class TOK {
  /* terminals */
  public static final int TK_rbrk = 34;
  public static final int RW_printf = 10;
  public static final int TK_equ = 26;
  public static final int TK_comma = 35;
  public static final int TK_notequ = 23;
  public static final int TK_rbrc = 32;
  public static final int TK_lessequ = 24;
  public static final int TK_string = 11;
  public static final int RW_int = 5;
  public static final int TK_equequ = 22;
  public static final int RW_float = 6;
  public static final int TK_colon = 36;
  public static final int RW_void = 3;
  public static final int TK_lpar = 29;
  public static final int TK_uminus = 21;
  public static final int TK_float = 14;
  public static final int TK_id = 15;
  public static final int EOF = 0;
  public static final int RW_goto = 9;
  public static final int error = 1;
  public static final int TK_more = 28;
  public static final int TK_int = 13;
  public static final int RW_include = 2;
  public static final int TK_lbrk = 33;
  public static final int TK_mult = 18;
  public static final int TK_lbrc = 31;
  public static final int TK_semicolon = 37;
  public static final int TK_div = 19;
  public static final int TK_less = 27;
  public static final int TK_moreequ = 25;
  public static final int RW_char = 4;
  public static final int TK_include = 12;
  public static final int TK_rpar = 30;
  public static final int RW_return = 8;
  public static final int RW_if = 7;
  public static final int TK_mod = 20;
  public static final int TK_minus = 17;
  public static final int TK_plus = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_include",
  "RW_void",
  "RW_char",
  "RW_int",
  "RW_float",
  "RW_if",
  "RW_return",
  "RW_goto",
  "RW_printf",
  "TK_string",
  "TK_include",
  "TK_int",
  "TK_float",
  "TK_id",
  "TK_plus",
  "TK_minus",
  "TK_mult",
  "TK_div",
  "TK_mod",
  "TK_uminus",
  "TK_equequ",
  "TK_notequ",
  "TK_lessequ",
  "TK_moreequ",
  "TK_equ",
  "TK_less",
  "TK_more",
  "TK_lpar",
  "TK_rpar",
  "TK_lbrc",
  "TK_rbrc",
  "TK_lbrk",
  "TK_rbrk",
  "TK_comma",
  "TK_colon",
  "TK_semicolon"
  };
}

